name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    # 1. Spin up an ephemeral Redis database in the cloud!
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      # 2. Added the 'redis' python package here
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pydantic pytest httpx mlflow scikit-learn==1.5.1 python-dotenv feast pyarrow redis
        
    - name: Run API Tests
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}  
      run: |
        python -m pytest tests/test_api.py